version: '3.4'

services:
  limbo.apiauthentication.testdatabase:
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    volumes:
     - testdatabase:/var/opt/mssql/data
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Express
     - SA_PASSWORD=iNg8oh!Ac8C-.jco.F82g
    ports:
     - "55010:1433" 

volumes:
  testdatabase: